In [1]:
# импортируем необходимые пакеты

import pandas as pd
import scipy
import numpy as np
from sklearn import datasets
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
# загружаем датасет
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
boston_data = pd.read_csv('data/housing.csv', header=None, delimiter=r"\s+", names=column_names)
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [3]:
# составим матрицу A и вектор целевой переменной
CRIM = boston_data['CRIM']
RM = boston_data['RM']
A = np.column_stack((np.ones(506), CRIM, RM))
y = boston_data[['PRICE']]
print(A)

[[1.0000e+00 6.3200e-03 6.5750e+00]
 [1.0000e+00 2.7310e-02 6.4210e+00]
 [1.0000e+00 2.7290e-02 7.1850e+00]
 ...
 [1.0000e+00 6.0760e-02 6.9760e+00]
 [1.0000e+00 1.0959e-01 6.7940e+00]
 [1.0000e+00 4.7410e-02 6.0300e+00]]


In [4]:
x1 = np.array([-0.535, -0.267, 0.802])
x2 = np.array([0.707, -0.707, 0])
A = np.array([x1, x2]).T
G = A.T @ A
np.round(G, 3)

array([[ 1.001, -0.189],
       [-0.189,  1.   ]])

In [5]:
A = np.matrix([
    [1, 1, 1],
    [1, 3, 9],
    [1, -2, 4],
    [1, 1, 1]
])
y = np.array([4, 5, 2, 2])
y = np.reshape(y, (4,1))
w = np.round(np.linalg.inv(A.T@A)*A.T@y, 2)
w

array([[2.4 ],
       [0.47],
       [0.13]])

In [6]:
A = np.matrix([
    [1, 1, 3, 1, 3, 9],
    [1, 3, 4, 9, 12, 16],
    [1, -2, 5, 4, -10 , 25],
    [1, 1, -2, 1, -2, 4],
    [1, 5, 4, 25, 20, 16],
    [1, 13, 11, 169, 143, 121],
    [1, 1, 3, 1, 3, 9]
])

y = np.array([4, 5, 2, 2, 6, 8, -1])
y = np.reshape(y, (7,1))
w = np.round(np.linalg.inv(A.T@A)@A.T@y, 2)
w

array([[-2.26],
       [ 2.38],
       [-0.13],
       [-0.1 ],
       [-0.27],
       [ 0.3 ]])

In [7]:
A = np.array([
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [4, 5, 2, 2, 6, 8, -1]
]).T
print(A)

[[ 1  3  4]
 [ 3  4  5]
 [-2  5  2]
 [ 1 -2  2]
 [ 5  4  6]
 [13 11  8]
 [ 1  3 -1]]


In [8]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True)

In [9]:
A_poly = poly.fit_transform(A)
display(pd.DataFrame(A_poly))

0     1     2    3      4      5      6      7     8     9
0  1.0   1.0   3.0  4.0    1.0    3.0    4.0    9.0  12.0  16.0
1  1.0   3.0   4.0  5.0    9.0   12.0   15.0   16.0  20.0  25.0
2  1.0  -2.0   5.0  2.0    4.0  -10.0   -4.0   25.0  10.0   4.0
3  1.0   1.0  -2.0  2.0    1.0   -2.0    2.0    4.0  -4.0   4.0
4  1.0   5.0   4.0  6.0   25.0   20.0   30.0   16.0  24.0  36.0
5  1.0  13.0  11.0  8.0  169.0  143.0  104.0  121.0  88.0  64.0
6  1.0   1.0   3.0 -1.0    1.0    3.0   -1.0    9.0  -3.0   1.0

In [10]:
def polynomial_regression(X, y, k):
    poly = PolynomialFeatures(degree=k, include_bias=True)
    X_poly = poly.fit_transform(X)
    w_hat = np.linalg.inv(X_poly.T@X_poly)@X_poly.T@y
    y_pred = X_poly@w_hat
    return X_poly, y_pred, w_hat

In [11]:
A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]
 
A_poly, y_pred, w_hat = polynomial_regression(A, y, 1)
A_poly2, y_pred2, w_hat2 = polynomial_regression(A, y, 2)
A_poly3, y_pred3, w_hat3 = polynomial_regression(A, y, 3)
A_poly4, y_pred4, w_hat4 = polynomial_regression(A, y, 4)
A_poly5, y_pred5, w_hat5 = polynomial_regression(A, y, 5)

In [12]:
from sklearn.metrics import mean_absolute_percentage_error
 
print('MAPE для полинома 1-й степени {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred)*100))
print('MAPE для полинома 2-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred2)*100))
print('MAPE для полинома 3-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred3)*100))
print('MAPE для полинома 4-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred4)*100))
print('MAPE для полинома 5-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred5)*100))

MAPE для полинома 1-й степени 18.20%
MAPE для полинома 2-й степени  13.41%
MAPE для полинома 3-й степени  12.93%
MAPE для полинома 4-й степени  10.75%
MAPE для полинома 5-й степени  384.42%


In [13]:
display(pd.DataFrame(w_hat5).describe())

PRICE
count     126.000000
mean      799.934638
std     23299.199090
min   -116549.849936
25%        -0.642205
50%        -0.000022
75%         1.112822
max    229784.415603

In [16]:
# считаем матрицу корреляций (без столбца из единиц)
C = pd.DataFrame(A_poly5[:, 1:]).corr()
# считаем ранг корреляционной матрицы
print('Ранг корреляционной матрицы:', np.linalg.matrix_rank(C))
# считаем количесво факторов (не включая столбец из единиц)
print('Количество факторов:', A_poly5[:,1:].shape[1])

Ранг корреляционной матрицы: 110
Количество факторов: 125


In [18]:
# считаем матрицу корреляций (без столбца из единиц)
C = pd.DataFrame(A_poly4[:,1:]).corr()
# считаем ранг корреляционной матрицы
print('Ранг корреляционной матрицы:', np.linalg.matrix_rank(C))
# считаем количество факторов (не включая столбец из единиц)
print('Количество факторов:', A_poly4[:,1:].shape[1])

Ранг корреляционной матрицы: 69
Количество факторов: 69


In [19]:
display(pd.DataFrame(w_hat4).describe())

PRICE
count    70.000000
mean    -50.908495
std     887.512886
min   -6926.807043
25%      -0.187947
50%      -0.000786
75%       0.322228
max    2305.380975

In [24]:
from sklearn.linear_model import LinearRegression
def polynomial_regression_sk(X, y, k):
    poly = PolynomialFeatures(degree=k, include_bias=True)
    X_poly=poly.fit_transform(X)
    lr = LinearRegression().fit(X_poly, y)
    y_pred = lr.predict(X_poly)
    return X_poly, y_pred, lr.coef_

A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]    

for k in range(1, 6):
    A_poly, y_pred, w_hat = polynomial_regression_sk(A, y, k)
    print('MAPE для полинома степени {} - {:.2f}%, СКО - {:.0f}'.format(
        k, mean_absolute_percentage_error(y, y_pred)*100, w_hat.std()
    ))

MAPE для полинома степени 1 - 18.20%, СКО - 2
MAPE для полинома степени 2 - 13.41%, СКО - 5
MAPE для полинома степени 3 - 12.93%, СКО - 9
MAPE для полинома степени 4 - 10.74%, СКО - 302
MAPE для полинома степени 5 - 9.02%, СКО - 16988


In [27]:
# task 6.1
def y(x1, x2):
    return 10.4 + 8*x1 + 0.5*x2 + 3*x1**2 + 0.4*x2**2 + 0*x1*x2

xnew = np.array([1, 4])
print(round(y(*xnew), 1))

29.8


In [30]:
# task 6.4
A = np.array([
    [1, 1, 1],
    [1, 3, 9],
    [1, -2, 4],
    [1, 9, 81] 
])
y = np.array([3, 7, -5, 21])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(np.round(w_hat, 1))

[ 0.1  2.5 -0. ]
