In [1]:
# импортируем необходимые пакеты

import pandas as pd
import scipy
import numpy as np


In [5]:
A = np.matrix("1, 1; 1, 2");
B = np.matrix("1, 1, 1; 1, 2, 2")
print('rank(A)={}'.format(np.linalg.matrix_rank(A)))
print('rank(B)={}'.format(np.linalg.matrix_rank(B)))
b = np.array([1, 2])
b = np.reshape(b, (2, 1))
print(np.linalg.inv(A)@b)

rank(A)=2
rank(B)=2
[[0.]
 [1.]]


In [8]:
# task 2.4
A = np.matrix("4, 7; 5, 10")
Ab = np.matrix("4, 7, 20; 5, 10, 30")
b = np.array([20, 30])
b = np.reshape(b, (2,1))
print('rank(A)={}'.format(np.linalg.matrix_rank(A)))
print('rank(Ab)={}'.format(np.linalg.matrix_rank(Ab)))
np.linalg.inv(A)@b

rank(A)=2
rank(Ab)=2


matrix([[-2.],
        [ 4.]])

In [16]:
# task 2.6
A = np.matrix("4, 7, -1; -4, 2, 5; 0, 9, 4")
Ab = np.matrix("4, 7, -1, 7; -4, 2, 5, 3; 0, 9, 4, 10")
print('rank(A)={}'.format(np.linalg.matrix_rank(A)))
print('rank(Ab)={}'.format(np.linalg.matrix_rank(Ab)))


rank(A)=2
rank(Ab)=2


In [18]:
# task 2.9
A = np.matrix("1, -5; 2, 1; 1, 1")
b = np.array([1, 2, 2])
b = np.reshape(b, (3, 1))
wp = np.array([1, 1])
wp = np.reshape(wp, (2,1))
bp = A@wp
e = b - bp
e

matrix([[ 5],
        [-1],
        [ 0]])

In [28]:
# task 2.11

A = np.matrix("1, 2; -3, 1; 1, 2; 1, -1")
G = A.T@A
b = np.array([1, 4, 5, 0])
b = np.reshape(b, (4,1))
print('G: ', G)
print('bp :', np.linalg.inv(G)@A.T@b)

G:  [[12  0]
 [ 0 10]]
bp : [[-0.5]
 [ 1.6]]


In [26]:
np.linalg.inv(G)

matrix([[0.08333333, 0.        ],
        [0.        , 0.1       ]])

In [27]:
A.T@b

matrix([[-6],
        [16]])